pipeline {
    agent any

    stages {
        stage('Dev') {
            steps {
                git 'https://github.com/KrisAff84/go-webapp-sample.git'
            }
        }

        stage('UAT') {
            steps {
                git 'https://github.com/KrisAff84/go-webapp-sample.git'
            }
        }
    }
}